### Get all orders
GET https://ticketing.dev/api/orders
Content-Type: application/json

### Create order
POST https://ticketing.dev/api/orders
Content-Type: application/json

{
  "ticketId": "id"
}

### Get order
GET https://ticketing.dev/api/orders/:orderId
Content-Type: application/json

### Cancel order
DELETE https://ticketing.dev/api/orders/:orderId
Content-Type: application/json